- hosts: all
  user: ubuntu
  gather_facts: True

  vars:
    owner:      OBOFoundry
    repo:       purl.obolibrary.org
    repo_url:   "https://github.com/{{ owner }}/{{ repo }}.git"
    image:      "{{ repo }}"
    tag:        latest
    creds:      ~/.s3cfg
    stage_dir:  /home/ubuntu/
    creds_dest: "{{ stage_dir }}/.s3cfg"
    repo_dest:  "{{ stage_dir }}/{{ repo }}"

  tasks:
    - name: Clone the Git repo
      git: repo={{ repo_url }} dest={{ repo }}
    - name: Build docker image
      shell: "docker build -f {{ repo }}/docker/Dockerfile -t {{ image }}:{{ tag }} {{ repo_dest }}"
    - name: Copy S3 credentials
      copy:
        src: "{{ creds }}"
        dest: "{{ creds_dest }}"
    - name: Copy docker compose template.
      template:
        src: docker-compose.yaml
        dest: "{{ stage_dir }}/docker-compose.yaml"
