language: python
python: "3.6"
install:
  - "sudo pip install ansible==2.10.7"
script:
  - "cd tools"
  - "echo 'localhost' > hosts"
  - "ansible-playbook -i hosts -e 'mode=travis' --connection=local site.yml"
  - "cd .."
  - "sudo cp -r `pwd` /var/www/purl.obolibrary.org"
  - "cd /var/www/purl.obolibrary.org"
  - "sudo make all test"
notifications:
  email:
    - james@overton.ca
    - cjmungall@lbl.gov
