idspace: ADO
base_url: /obo/ado

products:
- ado.owl: https://raw.githubusercontent.com/Fraunhofer-SCAI-Applied-Semantics/ADO/main/Releases/2.0.0/ADO.owl


term_browser: ontobee
example_terms:
- ADO_0000001

entries:

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/Fraunhofer-SCAI-Applied-Semantics/ADO/main/Releases/2022-06-11/
  
- prefix: /tracker/
  replacement: https://github.com/Fraunhofer-SCAI-Applied-Semantics/ADO/issues

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://github.com/Fraunhofer-SCAI-Applied-Semantics/ADO/tree/main/
