# PURL configuration for http://purl.obolibrary.org/obo/exo

idspace: ExO
base_url: /obo/exo

products:
- exo.owl: https://github.com/CTDbase/exposure-ontology/raw/master/exo.obo
- exo.obo: https://github.com/CTDbase/exposure-ontology/raw/master/exo.owl

term_browser: ontobee
example_terms:
- ExO_0000000
