# PURL configuration for http://purl.obolibrary.org/obo/ohd

idspace: OHD
base_url: /obo/ohd

base_redirect: https://github.com/oral-health-and-disease-ontologies/ohd-ontology

products:
- ohd.owl: https://raw.githubusercontent.com/oral-health-and-disease-ontologies/ohd-ontology/master/ohd.owl
- ohd-base.owl: https://raw.githubusercontent.com/oral-health-and-disease-ontologies/ohd-ontology/master/ohd-base.owl

term_browser: ontobee
example_terms:
- OHD_0000019

- prefix: /about/
  replacement: https://ontobee.org/ontology/OHD?iri=http://purl.obolibrary.org/obo/
  #tests:
  #- from: /about/OHD_0000019
  #  to: https://ontobee.org/ontology/OHD?iri=http://purl.obolibrary.org/obo/OHD_0000019
  
- prefix: /dev/
  replacement: https://github.com/oral-health-and-disease-ontologies/ohd-ontology/tree/master/src/ontology

## generic fall-through, serve direct from github by default
- prefix: /
  replacement: https://github.com/oral-health-and-disease-ontologies/ohd-ontology/tree/master/
