# PURL configuration for http://purl.obolibrary.org/obo/ornaseq

idspace: ORNASEQ
base_url: /obo/ornaseq

products:
- ornaseq.owl: https://raw.githubusercontent.com/safisher/ornaseq/v1.0/ornaseq.owl
- ornaseq.obo: https://raw.githubusercontent.com/safisher/ornaseq/v1.0/ornaseq.obo

term_browser: ontobee
example_terms:
- ORNASEQ_0000001
- ORNASEQ_0000002

entries:
- exact: /releases/2018-06-04/ornaseq.owl
  replacement: https://raw.githubusercontent.com/safisher/ornaseq/v1.0/ornaseq.owl

- exact: /releases/2018-06-04/ornaseq.obo
  replacement: https://raw.githubusercontent.com/safisher/ornaseq/v1.0/ornaseq.obo
