# PURL configuration for http://purl.obolibrary.org/obo/proco

idspace: PROCO
base_url: /obo/proco

products:
- proco.owl: https://raw.githubusercontent.com/proco-ontology/PROCO/v2022-04-11/proco.owl 

term_browser: ontobee
example_terms:
- PROCO_0000001

entries:
- exact: /v2022-04-11/proco.owl 
  replacement: https://raw.githubusercontent.com/proco-ontology/PROCO/v2022-04-11/proco.owl 
  
 
