# PURL configuration for http://purl.obolibrary.org/obo/uberon

idspace: UBERON
base_url: /obo/uberon

base_redirect: http://uberon.org

products:
- uberon.owl: http://ontologies.berkeleybop.org/uberon.owl
- uberon.obo: http://ontologies.berkeleybop.org/uberon.obo
- uberon.json: http://ontologies.berkeleybop.org/uberon.json

term_browser: ols
example_terms:
- UBERON_0000000

entries:
- exact: /phenoscape-ext-simple.obo
  replacement: https://stars-app.renci.org/jenkins/job/Phenoscape/job/build-phenoscape-ext-simple/lastSuccessfulBuild/artifact/phenoscape-ext-simple.obo

- exact: /phenoscape-ext.owl
  replacement: http://phenoscape.svn.sourceforge.net/svnroot/phenoscape/trunk/vocab/edit/phenoscape-ext.owl
  
- exact: /composite-vertebrate.owl
  replacement: https://github.com/obophenotype/uberon/releases/latest/download/composite-vertebrate.owl
  
- exact: /composite-vertebrate.obo
  replacement: https://github.com/obophenotype/uberon/releases/latest/download/composite-vertebrate.owl

- exact: /composite-metazoan.owl
  replacement: https://github.com/obophenotype/uberon/releases/latest/download/composite-metazoan.owl
  
- exact: /composite-metazoan.obo
  replacement: https://github.com/obophenotype/uberon/releases/latest/download/composite-metazoan.obo

- exact: /experimental/ceph.owl
  replacement: http://purl.obolibrary.org/obo/ceph.owl

- prefix: /references/
  replacement: https://raw.githubusercontent.com/obophenotype/uberon/master/reference/

- prefix: /homology/
  replacement: https://phenoscape.svn.sourceforge.net/svnroot/phenoscape/trunk/vocab/homology/

# Previously Uberon was releaseon on svn.code.sf.net. The following redirect essentially redirects any release pre-2020 (2019, 2018 etc) to that svn.
- prefix: /releases/201
   replacement: http://svn.code.sf.net/p/obo/svn/uberon/releases/201

- prefix: /releases/2020-05-06/
  replacement: http://svn.code.sf.net/p/obo/svn/uberon/releases/2020-05-06/

- prefix: /releases/2020-06-05/
  replacement: http://svn.code.sf.net/p/obo/svn/uberon/releases/2020-06-05/

- prefix: /releases/2020-09-16/
  replacement: http://svn.code.sf.net/p/obo/svn/uberon/releases/2020-09-16/

- prefix: /releases/
  replacement: https://raw.githubusercontent.com/obophenotype/uberon/v

- prefix: /tracker
  replacement: https://github.com/obophenotype/uberon/issues

- prefix: /about/
  replacement: https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http://purl.obolibrary.org/obo/
  tests:
  - from: /about/UBERON_0000981
    to: https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http://purl.obolibrary.org/obo/UBERON_0000981

- prefix: /docs
  replacement: https://github.com/obophenotype/uberon/wiki

- prefix: /
  replacement: https://raw.githubusercontent.com/obophenotype/uberon/master/

