name: Purl GitHub Actions

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 

jobs:
  DockertTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: false 
          tags: purl:latest

      - name: Run Tests 
        run: |
          docker run -v ${{ github.workspace }}:/var/www/purl.obolibrary.org -w /var/www/purl.obolibrary.org -t purl:latest sudo make all test

